export enum ItemErrorCode {
  ITEM_NOT_FOUND = 'ERR_ITEM_NOT_FOUND',
  ITEM_IS_INGREDIENT = 'ERR_ITEM_IS_INGREDIENT', // El error que te salía en texto
  DUPLICATE_SKU = 'ERR_DUPLICATE_SKU',
  DUPLICATE_BARCODE = 'ERR_DUPLICATE_BARCODE',
  DUPLICATE_ENTRY = 'ERR_DUPLICATE_ENTRY', // Genérico por si no detectamos el campo
  LIMIT_REACHED = 'ERR_ITEM_LIMIT_REACHED',
  BULK_LIMIT_EXCEEDED = 'ERR_BULK_LIMIT_EXCEEDED',
  PRO_FEATURE_ONLY = 'ERR_PRO_FEATURE_ONLY',
  INTERNAL_ERROR = 'ERR_INTERNAL_ERROR',
}
