export enum ProductType {
  RESALE = 'RESALE',
  PURCHASED_INGREDIENT = 'PURCHASED_INGREDIENT',
  PRODUCED_FINAL = 'PRODUCED_FINAL',
  PRODUCED_INGREDIENT = 'PRODUCED_INGREDIENT',
  HYBRID = 'HYBRID',
}
