// src/users/enums/user-error-code.enum.ts

export enum UserErrorCode {
  USER_NOT_FOUND = 'ERR_USER_NOT_FOUND',
  USER_NOT_AUTHENTICATED = 'ERR_USER_NOT_AUTHENTICATED',
  DELETE_ACCOUNT_FAILED = 'ERR_DELETE_ACCOUNT_FAILED',
  INTERNAL_ERROR = 'ERR_INTERNAL_ERROR',
}
